### ISSUE TITLE
Disable validation for disabled elements

### ISSUE THREAD

**Issue by Munhuggas** [dohomi/react-hook-form-mui#200]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

An element with both a `validation` prop and a `disabled` prop is still being validated.

### Expected behavior 🤔

Disabled elements should not be validated.

### Steps to reproduce 🕹

1. Create a form with for example a `DatePickerElement`.
2. Add a `validation` prop
3. Add a `disabled` prop
4. Submit the form
5. The validation is run even though the element is disabled

**Comment by dohomi** [comment]
Any PR is welcome. I would still think its probably straight forward to enable/disable the validation prop in the same way how you enable/disable the element itself.

**Comment by sadik-malik** [comment]
@dohomi, can we add a prop, such as 'novalidate,' to disable the validations defined inside components? This way, we can decide whether to keep the internal validations of react-hook-form-mui or not, irrespective of the 'disabled' prop."

Furthermore, @Munhuggas, I am really thinking about the scenario of why we are passing the 'validation' prop if we don't want to perform validation on a disabled element.

**Comment by Munhuggas** [comment]
@sadik-malik The common scenario for us is to not have to disable the element two times: once for input and once for validation. I am pretty sure the HTML standard has this setup although reading the documentation is a wild ride 😅 

I have tried to create a minimal example of this with HTML only. https://codepen.io/munhuggas/pen/VwgXbJq

**Comment by dohomi** [comment]
@Munhuggas similar to the previous comment of @sadik-malik I also state the same: you are not using HTML but React components, so if you set a required property on a disabled element, you can in the same time not pass the validation prop as you are aware of the state of validation at this point. It will add an overhead to be handled by this library which is in such a rare case not something I want invest too much time. Feel free to open a PR with your requested API changes otherwise I will close this for now as it is very easy to archive with a local state variable.

**Comment by Munhuggas** [comment]
@dohomi I might put up a PR in the future. I am merely trying to make you aware that the component does not behave intuitively. I could achieve most things with additional code, but the purpose of using a library is to avoid doing just that.

Anyway, thanks for your work and time to reply to my questions!
