### ISSUE TITLE
single Radio

### ISSUE THREAD

**Issue by sKopheK** [dohomi/react-hook-form-mui#229]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

hi, i'm missing possiblity to add a single Radio button instead of the whole group
use case: complicated layout when radio group can be applied

**Comment by dohomi** [comment]
This seems a rare case. Why not using a single item within the radio group? Seems for me more like to choose a checkbox for it

**Comment by sKopheK** [comment]
![imagen](https://github.com/dohomi/react-hook-form-mui/assets/5802917/8198b8cf-8ba7-431a-8bb9-2c4b0459b5c1)
my case - radio buttons within table as there can be any other component which can even span over more columns (i must admin i could use a different elements to wrap the controls but chose table for the sake of implementation simplicity)

MUI has it implemented (https://mui.com/material-ui/api/radio/), so i can use it in a standard Controller-render -> Radio composition

**Comment by dohomi** [comment]
I have to suggest that you use your own implementation for this use case, most likely you don't even have to use react-hook-form for this.. otherwise if you do, just run your own implementaion with `useForm` and use the `onChange` handler of each Radio to modify the value of your form state, this will be better performance than using `useController` on each radio. I assume you are not doing any validation so seems like a best solution for your table (also performance wise)

**Comment by sKopheK** [comment]
i did my own implementation as mentioned including validation, no worries - there's always a way ;) i understand it'd add unnecessary complexity because of a few edge cases

**Comment by dohomi** [comment]
> i did my own implementation as mentioned including validation, no worries - there's always a way ;) i understand it'd add unnecessary complexity because of a few edge cases

Great that you find a solution, make sure you dont run too many unnecessary renders with `useController` if you actually don't need to validate but simply want the final result in your onSubmit handler

**Comment by sKopheK** [comment]
I'm not using `useController`, just having MUI Radio wrapped in `Controller` component as I need to have it mapped with RHF
