### ISSUE TITLE
PasswordRepeat

### ISSUE THREAD

**Issue by AntalyanGriffin** [dohomi/react-hook-form-mui#36]
A core example [here ](https://react-hook-form-material-ui.vercel.app/?path=/docs/textfieldelement--core )mentions PasswordRepeat but nothing like that exists in the Storybook.

In fact, the solution is adding this piece of code from src to Storybook source code preview:
const PasswordRepeat: FunctionComponent = () => {
  const { getValues } = useFormContext()
  return (
    <PasswordElement margin={'dense'}
                     label={'Password Repeat'}
                     required
                     parseError={parseError}
                     validation={{
                       validate: (value: string) => {
                         const { password } = getValues()
                         return value === password || 'Password should match'
                       }
                     }}
                     name={'password-repeat'}
    />
  )
}

**Comment by dohomi** [comment]
@AntalyanGriffin the reference is this:
https://github.com/dohomi/react-hook-form-mui/blob/master/stories/TextFieldElement.stories.tsx#L35
It kind of depends on how you use this library. Since later versions of `react hook form` you can also use the `useWatch` hook to listen to changes of the password element.

**Comment by dohomi** [comment]
Resolved since v3.5.0 with `PasswordRepeatElement`
